### PR TITLE
add plottools submodule and modify folder structure

### PR DESCRIPTION
**Pull request by tsengshao**

### CODE REVIEW

**Comment by Aaron-Hsieh-0129** [comment]
Modify docs/source/api/vvmtools/vvmtools.rst to the following content to make the website function properly.
Basically it's the same as what you've just done, and we just didn't change the autoclass to vvmtools.VVMTools.VVMTools


```rst
VVMTools Class
==============


.. autoclass:: vvmtools.VVMTools.VVMTools
   :exclude-members: get_var, get_var_parallel, func_time_parallel



Attributes
----------

.. autosummary:: 
   :toctree: attribute
   :nosignatures:

   vvmtools.VVMTools.VVMTools.VARTYPE

- **VARTYPE**: Dictionary of variable types
- **DIM**: Dictionary of spatial dimensions
- **INIT**: Dictionary of initial profile data
- **time_array_str**: Array of time values

Methods
-------

.. autosummary::
   :toctree: generated

   vvmtools.VVMTools.VVMTools.get_var
   vvmtools.VVMTools.VVMTools.get_var_parallel
   vvmtools.VVMTools.VVMTools.func_time_parallel

```

**Comment by Aaron-Hsieh-0129** [comment]
btw, if the building process is correct, you'll see the documentation is built successfully in the github actions page. You can see it shows wrong for the add_plotters branch for now.

**Comment by tsengshao** [comment]
the original website is available. please check ~

**Comment by Aaron-Hsieh-0129** [comment]
Nice

**Pull request merged**
